spring:
  main:
    banner-mode: 'off'
thymeleaf:
  cache: false
server:
  port: 8888
# openweathermap:
#   appid: xxx
management:
  endpoints:
    web:
      base-path: /manage
togglz:
  features:
    FEATURE_COMMENTAIRE:
      enabled: false
  console:
    enabled: true
    secured: false
    use-management-port: false
    path: /manage/features
